# Collective
# ----------

# Define the Open Collective you want to link the repository with.
# Use the slug not an URL.

collective: backyourstack

# Examples

# collective: webpack

# Invalid examples

# collective: https://opencollective.com/webpack
# collective: opencollective.com/webpack
# collective: https://opencollective.com/webpack/contribute/backer-266

# Invitation
# ----------

# Post a comment on issues created by non contributors.

invitation: |-
  Hey <author> :wave:,

  Thank you for opening an issue. We will get back to you as soon as we can. Also, check out our Open Collective and consider contributing financially.

  <link>

  > PS.: We offer `priority` support for all financial contributors. Don't forget to add `priority` label once you start contributing :smile:

# Tiers
# -----

# In this section you can define specific behavior for all supported tiers,
# ie: "backer" "and sponsor".
